### ISSUE TITLE
Update docs to reference new global tracking snippet

### ISSUE THREAD

**Issue by tyrp** [RootsRated/support-documentation#12]

**Comment by bpapillon** [comment]
I just went through this process on rootsrated.media and it works well. I took screenshots along the way and these are the steps:

1. Go to [Google Tag Manager](https://tagmanager.google.com)
2. Select workspace
3. Navigate to "Tags" and click "New"
4. Replace the placeholder title with "Compass"
5. Hover over "Tag Configuration" and click the pen icon to configure the new tag
6. Select "Custom HTML" under "Custom"
7. Copy the your global snippet from the top of the [Compass settings page](https://compass.rootsrated.com/settings/integrations) and paste it into the "HTML" field in the Google Tag configuration form
8. Scroll down to the "Triggering" section, click it, and select "All Pages"
9. Click "Save" to save your tag configuration
10. To enable these changes on your site, click "Submit" in the top right, add a descriptive name to your changes, and then click "Publish"
11. You now have the Compass global snippet installed on your site, and are up and running for publishing content, tracking content-influenced leads, and more!

Next step is to wordsmith this a bit and then add it to the docs site along with the screenshots.

**Comment by bpapillon** [comment]
It's alive!!!!! https://docs.rootsrated.com/Setup/tracking-code/
