### ISSUE TITLE
Empty docs page

### ISSUE THREAD

**Issue by bpapillon** [RootsRated/support-documentation#8]
What is supposed to be on this page?
https://docs.rootsrated.com/Marketing/agency-access/

**Comment by bpapillon** [comment]
@wleklinski do you know anything about this page (what should be on it) or should I check with Jas?

**Comment by wleklinski** [comment]
I think the page may have been removed when we clarified our target customer, but the link remains?

**Comment by bpapillon** [comment]
That seems possible. Do you think it's reasonable for me to just nuke this page?

**Comment by jasdeepg** [comment]
We no longer request agency access ... just page access. Can probably nuke. Jordan just lists out steps to a partner rather than referring to docs.
